name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma_accelerate_url"
JWT_KEY = "your_jwt_password"
saltRounds = 10

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
